import { phone } from "@/data/siteData";
import { useRoute, Link } from "wouter";
import { ArrowRight, ArrowUpRight } from "lucide-react";
import { designSteps, materials, projects } from "@/data/siteData";
import { CallLink, ArrowLink, Eyebrow, Media, PageMeta, SectionLabel } from "@/components/site/Primitives";

export function InteriorDesignPage() {
  return <>
    <PageMeta meta={{ title: "Interior Design — HOUZZ STUDIOS", description: "Thoughtful residential and commercial interior design, from first conversation through material, making and handover." }} />
    <section className="service-hero"><div className="service-hero__image"><Media src="/images/warm-interior.jpg" alt="Warm residential interior with custom timber and soft natural light" priority /></div><div className="service-hero__copy"><Eyebrow>INTERIOR DESIGN / RESIDENTIAL & COMMERCIAL</Eyebrow><h1>Spaces made<br />to feel <em>like yours.</em></h1><p>We shape thoughtful interiors around the way you live and work—considered in every detail, generous in every day.</p><ArrowLink href="/contact">Begin a design conversation</ArrowLink><span className="service-hero__index">DESIGN STUDIO · 01</span></div></section>

    <section className="service-philosophy section-pad"><SectionLabel number="01">THE IDEA</SectionLabel><div className="service-philosophy__content"><h2>Beautiful is a beginning.<br /><em>Living well is the point.</em></h2><p>We believe the best interiors make room for real life. They hold the things you love, make everyday movement feel easy and let materials age with grace. The work is a conversation between your rhythms and a place’s natural character.</p><span className="service-philosophy__line" /></div></section>

    <section className="process-section section-pad"><div className="process-section__heading"><Eyebrow>HOW WE WORK</Eyebrow><h2>Considered at<br /><em>every step.</em></h2><p>A clear process keeps the work open, collaborative and grounded in how you will use the space.</p></div><div className="process-timeline">{designSteps.map((step, index) => <article className="process-step" key={step.number}><div className="process-step__number"><span>{step.number}</span><i /></div><div><h3>{step.title}</h3><p>{step.text}</p></div><span className="process-step__ghost">0{index + 1}</span></article>)}</div></section>

    <section className="service-typologies section-pad"><div className="typology-heading"><Eyebrow>PLACES TO LIVE & GATHER</Eyebrow><h2>Different ways<br />to <em>belong.</em></h2></div><article className="typology-feature typology-feature--residential"><Link className="typology-feature__image" href="/projects/modern-apartment"><Media src="/images/apartment.jpg" alt="A warm, naturally lit residential interior with oak details" /><span className="typology-feature__label">01 / RESIDENTIAL</span></Link><div className="typology-feature__copy"><span className="eyebrow">RESIDENTIAL</span><h3>A home that<br /><em>feels like home.</em></h3><p>Personal, practical interiors that respond to the people who inhabit them. From a single room to a whole home, our focus stays on the details that make a space yours.</p><ArrowLink href="/projects/modern-apartment">View a residential study</ArrowLink></div></article><article className="typology-feature typology-feature--commercial"><div className="typology-feature__copy"><span className="eyebrow">COMMERCIAL</span><h3>Spaces to<br /><em>do good work.</em></h3><p>Welcoming work and hospitality environments that balance clarity, comfort and character—made for the way people meet, move and focus.</p><ArrowLink href="/projects/contemporary-office">View a commercial study</ArrowLink></div><Link className="typology-feature__image" href="/projects/contemporary-office"><Media src="/images/commercial-loft.jpg" alt="A considered contemporary workspace with warm timber and stone" /><span className="typology-feature__label">02 / COMMERCIAL</span></Link></article></section>

    <section className="service-materials"><div className="service-materials__copy"><Eyebrow>THE MATERIAL CONVERSATION</Eyebrow><h2>Start with<br /><em>what lasts.</em></h2><p>We choose materials for their presence and their patience: natural wood, honest stone, durable weaves and careful joinery.</p><ArrowLink href="/about">Our approach to craft</ArrowLink></div><div className="service-materials__samples">{materials.slice(0, 3).map((material, index) => <figure className={`material-sample material-sample--${index + 1}`} key={material.name}><Media src={material.image} alt={`${material.name.toLowerCase()} material study`} /><figcaption><span>0{index + 1}</span>{material.name}</figcaption></figure>)}</div></section>

    <section className="selected-work section-pad"><div className="selected-work__heading"><div><Eyebrow>SELECTED WORK</Eyebrow><h2>A few spaces,<br /><em>many stories.</em></h2></div><ArrowLink href="/projects">Explore all projects</ArrowLink></div><div className="selected-work__list">{projects.slice(0, 2).map((project, index) => <Link key={project.slug} href={`/projects/${project.slug}`} className={`selected-work__item selected-work__item--${index + 1}`}><Media src={project.image} alt={`${project.name} project in ${project.location}`} /><span className="selected-work__meta"><span>0{index + 1} · {project.location.toUpperCase()}</span><strong>{project.name}</strong><ArrowUpRight size={18} /></span></Link>)}</div></section>

    <section className="service-cta"><div><Eyebrow light>YOUR SPACE, NEXT</Eyebrow><h2>It begins with<br /><em>a conversation.</em></h2><p>Tell us a little about the place you are imagining. We’ll take it from there, together.</p><Link className="button button--light" href="/contact">Book a Consultation <ArrowRight size={16} /></Link> <CallLink className="hero-text-link service-cta__call">Or call {phone.display}</CallLink></div><span className="service-cta__mark">H<br />S</span></section>
  </>;
}

export function ProjectsPage() {
  return <>
    <PageMeta meta={{ title: "Selected Projects — HOUZZ STUDIOS", description: "Explore illustrative residential and commercial visual studies for New York, Los Angeles and Austin. Images are not documentary project photography." }} />
    <section className="projects-page-intro section-pad"><Eyebrow>OUR PROJECTS / SELECTED WORK</Eyebrow><div className="projects-page-intro__row"><h1>Real spaces.<br /><em>Real stories.</em></h1><p>Every project begins with a conversation, then finds its shape in material, light and the lives that unfold inside it.</p></div><span className="projects-page-intro__index">RESIDENTIAL / COMMERCIAL<br />2024—2025 · USA</span><small className="projects-page-intro__disclosure">ILLUSTRATIVE VISUAL STUDIES · NOT DOCUMENTARY PROJECT PHOTOGRAPHY</small></section>
    <section className="project-archive section-pad">{projects.map((project, index) => <Link key={project.slug} href={`/projects/${project.slug}`} className={`archive-project archive-project--${index + 1}`}><div className="archive-project__image"><Media src={project.image} alt={`${project.name}, ${project.type.toLowerCase()} project in ${project.location}`} /><span className="archive-project__number">0{index + 1}</span><span className="archive-project__arrow"><ArrowUpRight size={17} /></span></div><div className="archive-project__caption"><div><span className="eyebrow">{project.type.toUpperCase()} · {project.year}</span><h2>{project.name}</h2></div><span>{project.location}</span></div><p className="archive-project__summary">{project.summary}</p></Link>)}</section>
    <section className="projects-page-end"><span>THOUGHTFULLY MADE · 03 STUDIES</span><ArrowLink href="/contact">Discuss a project</ArrowLink></section>
  </>;
}

export function ProjectDetailPage() {
  const [, params] = useRoute("/projects/:slug");
  const project = projects.find((item) => item.slug === params?.slug);
  if (!project) return <section className="simple-not-found section-pad"><Eyebrow>PROJECT NOT FOUND</Eyebrow><h1>Every story has<br /><em>a way back.</em></h1><ArrowLink href="/projects">Return to projects</ArrowLink></section>;
  return <>
    <PageMeta meta={{ title: `${project.name}, ${project.location} — HOUZZ STUDIOS`, description: `${project.summary} Illustrative visual study, not documentary project photography.`, type: "article" }} />
    <section className="case-study-hero"><Media src={project.image} alt={`${project.name} illustrative interior visualization in ${project.location}`} priority /><div className="case-study-hero__shade" /><div className="case-study-hero__copy"><Eyebrow light>{project.type.toUpperCase()} · {project.location.toUpperCase()} · {project.year}</Eyebrow><h1>{project.name}<br /><em>{project.location}</em></h1></div><span className="case-study-hero__folio">ILLUSTRATIVE STUDY · NOT DOCUMENTARY · 0{projects.indexOf(project) + 1}</span></section>
    <section className="case-study-intro section-pad"><SectionLabel number="01">THE BRIEF</SectionLabel><div><p className="lead-serif">{project.summary}</p><p>{project.concept}</p></div><div className="case-study-spec"><span>LOCATION</span><strong>{project.location}</strong><span>YEAR</span><strong>{project.year}</strong><span>TYPE</span><strong>{project.type}</strong></div></section>
    <section className="case-study-image"><Media src={project.gallery[0]} alt={`Material and living detail from ${project.name}`} /><span>02 / MATERIAL IN THE MORNING LIGHT</span></section>
    <section className="case-study-materials section-pad"><div><Eyebrow>MATERIAL NOTES</Eyebrow><h2>Quietly<br /><em>considered.</em></h2><p>Each surface was chosen for its character, tactility and ability to feel at home in the room.</p></div><div className="case-study-materials__list">{project.materials.map((material, index) => <div key={material}><span>0{index + 1}</span><p>{material}</p><i /></div>)}</div></section>
    <section className="case-study-gallery section-pad"><figure className="case-study-gallery__large"><Media src={project.gallery[1]} alt={`Craft detail from ${project.name}`} /><figcaption>03 / DETAIL & CRAFT</figcaption></figure><div className="case-study-gallery__note"><Eyebrow>THE FINER GRAIN</Eyebrow><p>Designed to settle in, not to stand apart. A thoughtful rhythm of texture, light and useful form.</p></div></section>
    <section className="related-projects section-pad"><div><Eyebrow>ANOTHER POINT OF VIEW</Eyebrow><h2>Continue<br /><em>the story.</em></h2></div><div>{projects.filter((item) => item.slug !== project.slug).slice(0, 2).map((item) => <Link key={item.slug} href={`/projects/${item.slug}`}><span>{item.location} · {item.type}</span><strong>{item.name}</strong><ArrowUpRight size={17} /></Link>)}</div></section>
    <section className="page-cta-strip"><div><Eyebrow>HAVE A SPACE IN MIND?</Eyebrow><h2>Let’s make room<br /><em>for what matters.</em></h2></div><ArrowLink href="/contact">Start a conversation</ArrowLink></section>
  </>;
}
